README.md
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
pom.xml

Update docs. Fixes #14

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VersionData.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHMetaData.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MetadataSerializationTest.kt

Allow modification of metadata without serialisation errors

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Exclude debug info from assets

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortOrder.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt

Add ability to change sort order of results

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortOrder.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt

depends on #24 so merge that first

Add latest assets path

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortOrder.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt

Tidy swagger ui documentation for sort order

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt

Fix test path

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt

actually show latest asset path in swagger

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/BinaryAssetView.kt

add release_name to the latest asset

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt

Sort node order when stored for efficiency. Check checksum is not empty

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/filters/BinaryFilter.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Project.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/Mapper.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHMetaData.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MetadataSerializationTest.kt

Exclude jfr from api

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Fix error on an unparsable version

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Default upstream assets to jdk image type

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VersionData.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt

sort by version rather than just time stamp

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt

Fix downloading old checksum

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Fix parsing releasetype on -binary repos

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Release.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/SourcePackage.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamReleaseMapperTest.kt

Possible solution to #31

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Delay github pull to avoid hitting rate limit

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Asset.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Installer.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Package.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt

Add signature_link to package. Add test to assert sort order. Tidy up VersionParser

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt

Tidy up and eagerly fetch datastore

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStats.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DownloadStats.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DownloadStatsDbEntry.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DownloadStatsCalculator.kt

Begin collecting download stats over time

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/GithubDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt

Add docker stats

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DownloadStats.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt

Add total stats route

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt

Exclude upstream stats

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

fix docker stats and add test

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Asset.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DbStatsEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/GithubDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Installer.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Package.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt

Fix download stats. Show release name on total route

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

Remove cache as it seems to be killing mongo

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

Retry on http failure

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

Bring back cache

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Back off rate limit

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Millis to seconds

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

Exclude unparsable releases from update

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

Limit parallelism

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Reduce number of threads created

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Hold off retrys when quota is low

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Set minimum backoff to 10 sec

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/TestResourceGenerator.kt

Set floor on api quota usage

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

add timeout

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

fix exception

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedHtmlClient.kt

increase threads

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GithubAuth.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Add auth for http downloads

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt

Print error

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt

Add logging

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt

Add index to cache

---

adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/resources/log4j2.properties
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Move to apache httpasyncclient as Javas Async client may have a show stopping bug

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/GraphQLGitHubClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Use exceptions rather than null to propegate errors and avoid recording bad stats

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DownloadDiff.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt

Make date a full date time

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/StatsSource.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt

add tracking stats filter

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt

Throw exception outside async

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt

Try setting error message

---

.github/workflows/build.yml

add code coverage

---

.github/workflows/build.yml
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-persistance/pom.xml
pom.xml

Coverage test

---

.github/workflows/build.yml
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-persistance/pom.xml
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
pom.xml

Add code coverage stats

---

.github/workflows/build.yml
README.md
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-persistance/pom.xml
pom.xml

Merge Staging into Master

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/resources/example-release.json

Fix version parsing from metadata

---

adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt
adoptopenjdk-api-v3-updater/pom.xml

Move tests for better stats

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/resources/example-release.json

Fix version parsing from metadata file

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/resources/example-release.json

Ignore young artifacts

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt

Ignore artifacts while they are still uploading to avoid partial datasets

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequestInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubRepositoryClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubSummaryClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/summary/GHReleaseSummary.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GraphQLGitHubClientTest.kt

Fix githubs broken updatedAt on releases

---

adoptopenjdk-api-v3-frontend/pom.xml

add upload goal

---

adoptopenjdk-api-v3-frontend/pom.xml

Move to package

---

.s2i/bin/assemble
adoptopenjdk-api-v3-frontend/pom.xml

Put swagger deploy into script

---

.s2i/bin/assemble

switch if statement logic

---

.github/workflows/build.yml
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt

Add javascript client generation, Add types

---

.github/workflows/build.yml
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GithubAuth.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Fix warnings that may be killing builds

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt

enforce day limit

---

.github/workflows/build.yml
.s2i/bin/assemble
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GithubAuth.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Merge updates from master into staging

---

.s2i/bin/assemble

Remove log from built image

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CacheDbEntry.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt

Use Last-Modified and If-Modified-Since to reduce request burden

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt

Pass on lastModified header when url is redirected

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/resources/logback.xml

Add printing debug stats to narrow down missing stats issues

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Possible fix for #117 and #116

Take the last version in the release as the release version

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

If there are multiple stat entries for a single day, take the last

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt

add timeout to Http requests

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/filters/BinaryFilter.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Project.kt

Sync master and staging

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/BinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/TestResourceGenerator.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamReleaseMapperTest.kt

Filter non-binary assets in stats

---

.s2i/bin/assemble
scripts/healthCheck.sh

add health check script

---

.s2i/bin/assemble
scripts/healthCheck.sh

Bring health check from staging into master

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ImageType.kt

Add support for debug images

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt

Add's links to V2 and deprecation notice

add description to top of swagger doc

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt

Exclude debug images from live until we are ready to go live

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt

Keep bad stats in staging instance so we can diagnose reporting issues

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/FeatureRelease.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/GithubId.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GitHubApi.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/GraphQLGitHubClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequestInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHRelease.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GithubIdDeserializer.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/summary/GHReleaseSummary.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamReleaseMapperTest.kt

Split releases with a mix of versions, resolving #120

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Prevent double counting stats when splitting releases

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt

remove beta tag

---

adoptopenjdk-api-v3-updater/pom.xml

Bump httpcore to fix https://issues.apache.org/jira/browse/HTTPCORE-583

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt

Add debugging logic to http cache

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/JsonMapper.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/TimeSource.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterJsonMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt

Fix incorrect updated release check

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt

Cache update issues seem resolved by #142

Bring back cache update

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/JsonSerializationTest.kt

Pretty print returned json

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/GithubId.kt

Fix equality of GithubIds

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/BinaryAssetView.kt

add version data to BinaryAssetView

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/PlatformsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseNamesPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VariantsPathTest.kt

Add more tests

---

.editorconfig
.github/workflows/build.yml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt

Add head request for gradle download

---

.mvn/wrapper/maven-wrapper.properties
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/DayMeter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/StatsInterceptor.kt
adoptopenjdk-api-v3-persistance/pom.xml
adoptopenjdk-api-v3-updater/pom.xml
pom.xml

Add metrics

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortOrder.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/JvmImpl.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/OperatingSystem.kt

Remove example values so they are not pre-filled in swagger-ui

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt

Merge Fix #171 into master

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GithubAuth.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GitHubAuthTest.kt
codecov.yml

more tests/coverage

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/GithubAuth.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GitHubAuthTest.kt
codecov.yml

Merge master into staging

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/BinaryFilter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt

add date filter to feature_releases path

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

add pre to the release version split

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt

Print binary size statistics

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Add upstream jfr fix to staging

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ImageType.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Add static-libs as recognized ImageType for upstream

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ImageType.kt

fix displaying correct value in swagger-ui

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt

Bring staging in line with master

---

CONTRIBUTING.md
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-updater/pom.xml
gradle/wrapper/gradle-wrapper.properties
pom.xml

Pretty major overhaul which allows for site generation amongst other things.
One issue outstanding is that I run across something similar to:
https://stackoverflow.com/questions/6308162/maven-the-packaging-for-this-project-did-not-assign-a-file-to-the-build-artifac when running `mvn clean install` from the top level

Overhaul of Maven files + initial CONTRIBUTING.md

---

docs/STRUCTURE.md

Initial project stucture doc

---

adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
pom.xml

Fix tests not shutting down fongo

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
CONTRIBUTING.md
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
docs/STRUCTURE.md
gradle/wrapper/gradle-wrapper.properties
pom.xml

Merge master changes into staging

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt

Possible solution to #209 on staging

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/HeapSize.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt

add LinuxLH, fixes #204

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamBinaryMapperTest.kt

Release installer paths from staging

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json

add jdk 15

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Remove 14.0.1+7.1 and 15.0.0+24.1 nightlies from the api

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ReleaseInfo.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt

Add tip version to available versions. Fixes #221

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Dont propagate exception and prevent incremental updates

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Throw correct exception type when failing to parse a release

---

.gitignore
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/MonthlyStatsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DockerDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/GithubDownloadStatsDbEntry.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/MonthlyDownloadDiff.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/GithubDownloadStatsCalculator.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt

Merge stats updates from staging

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/JsonSerializationTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseNamesPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/HeapSize.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ReleaseInfo.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpstreamReleaseMapperTest.kt

Merge master into staging (dont squash/rebase)

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/platforms.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt

* WIP add riscv64
* Exclude riscv from test set

Add riscv architecture to api (#229)

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Closes: #231 
Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

Fix regex pattern

---

adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html

Closes: #186 
Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

Added link to structure.md

---

adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Take staging live

---

CONTRIBUTING.md

Fix link to STRUCTURE.md doc

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortMethod.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt

allow caller to set sort method

---

adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/resources/ApplicationInsights.xml

add debug logging for application insights

---

.s2i/bin/assemble

Fix packaging

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsInterceptor.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsTelemetery.kt
adoptopenjdk-api-v3-frontend/src/main/resources/ApplicationInsights.xml

Rework sampling to track full request time

---

.s2i/bin/assemble

Prevent failed build from passing

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt

print update stats for debugging

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/TestRunner.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoAPIPersistenceTests.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/UpdateRunner.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt

Add update time to db and poll updates more frequently

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt

Stream checksum digest to try to avoid running out of memory

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V3Test.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/APIDataStoreTest.kt

Prevent updater from scheduling updates

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt

Make UpdatedInfo a data class

---

.adr-dir
CONTRIBUTING.md
docs/adr/0001-record-architecture-decisions.md

Add support for ADRs within the project structure

---

adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/resources/logback.xml
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-persistance/pom.xml
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/resources/logback.xml
pom.xml

Add application insights log appender

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json

Bump to 16

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt

Log all errors before exit

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt

Add release_name path

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
adoptopenjdk-api-v3-persistance/src/test/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClientTest.kt

fix defaulting mongo connection string settings

---

adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Ensure tests are not dependent on the time of day they are run

---

.github/workflows/build.yml

upload generated javascript library

---

README.md

Add section to README highlighting key use-cases for the API

---

FAQ.md
README.md

Create the FAQ document.
Not sure whether what I've currently put in there is completely accurate so review would be useful.
Fixes #296

FAQ section

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Project.kt

Remove Project schema duplication

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Release.kt

Library already generates these values

Remove unneeded annotations

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/OperatingSystem.kt

add alpine-linux as a linux alternative

---

.github/workflows/build.yml
speccy.yaml

add speccy openapi linting

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/OperatingSystem.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt

Make alpine-linux a seperate os

---

README.md

Looks like the dashboard has moved, fixing the link in the README

Fix dashboard link

---

pom.xml

Bump applicationinsights

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V1RouteTest.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubRepositoryClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubSummaryClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGitHubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/GraphQLGitHubReleaseClientTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt

Move http clients over to DI

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptReposBuilder.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/summary/GHReleaseSummary.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/V3UpdaterTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/testDoubles/AdoptRepositoryStub.kt

Fix multiple incremental updates happening in parrallel

---

README.md

Remove dead link to API v1 README
Fixes #293

Update README to state that API v1 has been removed

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CacheDbEntry.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGitHubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/CachedGitHubHtmlClientTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/testDoubles/InMemoryInternalDbStore.kt

Reduce the frequency of html cache refreshes to once a day/week

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt

Merge internal sorting and version logging changes

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CacheDbEntry.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGitHubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/InternalDbStoreTests.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoAPIPersistenceTests.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/testDoubles/InMemoryInternalDbStore.kt

Set cache checked time when data has not changed

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Release.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStoreImpl.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/ApiPersistence.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoApiPersistence.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/UpdatedInfo.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/main/resources/logback.xml
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/InternalDbStoreTests.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/MongoAPIPersistenceTests.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/testDoubles/InMemoryApiPersistence.kt
scripts/healthCheck.sh

prevent download count causing checksum miss matches

---

.s2i/bin/assemble
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Release.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/SourcePackage.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VersionData.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt

Remove logs dir from build

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/config/APIConfig.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt

Fix equals hashcode checks not calculating equality correctly

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DateTime.kt

Fix DateTime parse to be inclusive of date

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt

Fix version-number location

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/DateTime.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DateTimeMigrationTest.kt

Fix incorrect serialization

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt

Set JDK 15 to be not obsolete

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json

enable java 17

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ApiDataStoreStub.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ReleaseInfo.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Variant.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/JsonMapper.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStoreImpl.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterJsonMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
pom.xml

Remove obsolete pending adding vendor specific rules

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsInterceptor.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ApiDataStoreStub.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ReleaseInfo.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Variant.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/JsonMapper.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStoreImpl.kt
adoptopenjdk-api-v3-telemetry/src/main/kotlin/net/adoptopenjdk/api/v3/ai/AppInsightsTelemetry.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterJsonMapper.kt
adoptopenjdk-api-v3-updater/src/main/resources/logback.xml
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
pom.xml

Fix application insights logging of binary requests. GZIP output. Bump quarkus version

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt

 Remove duplicate access-control-allow-origin header

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt

Format date times correctly for output

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt

Ensure we default to adoptopenjdk as a vendor

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt

Ensure we default to adoptopenjdk as a vendor (#386)

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/AdoptRepos.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/BinaryAssetView.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Vendor.kt

Closes: #365 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

Add vendor object to latest endpoint

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt

add missing test for defaulting vendor

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt

* Allows OpenAPI to produce drop down documentation
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

Remove schema from vendor latest

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/ReleaseEndpoint.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionsPathTest.kt

Add additional parameters to release_names and release_versions endpoints

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt

For frontend requests make x86 map to x32

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-updater/src/main/resources/JSON
adoptopenjdk-api-v3-updater/src/main/resources/JSON/platforms.json
adoptopenjdk-api-v3-updater/src/main/resources/JSON/variants.json
pom.xml

#370 : increased default page size for `release_versions` end-point

---

adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt

Reduce the amount of test data generated

---

.s2i/bin/assemble
pom.xml

Remove upstream repo and fix build

---

adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Fix setting the correct vendor on temurin repo

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsPathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceReleaseNamePathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/FrontendTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/LatestAssetsPathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
pom.xml

Merge in latest from adoptium

---

adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt

Use correct mapper for adoptopenjdk

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

exclude the release jdk-2021-01-13-07-01

---

adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Merge jdk-2021-01-13-07-01 patch

---

adoptopenjdk-updater-parent/adoptopenjdk-datasources-parent/adoptopenjdk-github-datasource/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubInterface.kt

Fix server timeout from graphql

---

.s2i/bin/assemble
pom.xml

Merge master to prod

---

scripts/frontendHealthCheck.sh

Add frontend health check

---

.s2i/bin/assemble
scripts/frontendHealthCheck.sh

Bring in frontend health check

---

.s2i/bin/assemble
scripts/frontendHealthCheck.sh

Make health check executable

---

.s2i/bin/assemble
scripts/frontendHealthCheck.sh

Make monitoring scripts executable

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt

Fix vendor filter not showing semeru builds

---

Dockerfile
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Startup.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DbExtension.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V3Test.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/pom.xml
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruMapperTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruReleaseMapperTest.kt
pom.xml

Bump vertx

---

.github/workflows/build.yml
quarkus-patch/patch-quarkus.sh
quarkus-patch/release.patch

Patch quarkus until a fix is released

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/ReleaseFilter.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/AdoptVendor.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/AdoptiumVendor.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Vendor.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/AdoptRepository.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTestDataGenerator.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruMapperTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/SemeruReleaseMapperTest.kt

 rename adoptium vendor to eclipse

---

.s2i/bin/assemble

Add quarkus patch to build

---

scripts/frontendHealthCheck.sh

Remove restart

---

adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Versions.kt

add 17 to lts list
