AdoptOpenJDK/openjdk-api-v3

adoptopenjdk-api-v3-frontend/src/main/resources/application.properties

Vertx on Openshift is throwing exceptions, see (https://github.com/eclipse-vertx/vert.x/issues/1931). Trying to disable cache as a fix.

Disable file caching on openshift

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/filters/BinaryFilter.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Project.kt

This should fix #112. I believe the presence of both jdk and jfr binaries inside the release meant that the api was unable to determine which binary to return.
Fixed by defaulting to the jdk project type when none is provided.
This will have the consequence of meaning that jfr builds will not be returned by default to the website and if we want them on the website will have to be retrieved via a separate call, @gdams may want to confirm that is ok.

Default the project type to jdk when none is provided

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CacheDbEntry.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/CachedGithubHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/mongo/InternalDbStore.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptMetadataVersionParsingTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt

Merge in latest updates from staging

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/HttpClientFactory.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/UpdaterHtmlClient.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/DockerStatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
adoptopenjdk-api-v3-updater/src/main/resources/logback.xml
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt

Add recent updates from staging
- Add timeout to http requests
- When multiple stats entries are present for a single day, take the last
- Debug print stats issues

Bring #124, #114 and #111 from staging into master

---

adoptopenjdk-api-v3-frontend/src/main/resources/META-INF/resources/index.html

update v3 readme to include deprecation information

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/V1Route.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V1RouteTest.kt

Add v1 reject frontend

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt

Ignore optional parts of the version string when splitting releases to avoid over splitting nightlies

When grouping releases, ignore optional values

---

adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt

When parsing `jdk-11.0.7-ea+9_openj9-0.20.0` version produced looks as follows:
```
{
"adopt_build_number" : null,
"build" : 9,
"major" : 11,
"minor" : 0,
"openjdk_version" : "11.0.7-ea+9",
"optional" : null,
"pre" : "ea",
"security" : 7,
"semver" : "11.0.7-ea+9"
}
```

add test for aarch ea version string

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionPathTest.kt

add more bad tests for better coverage

---

.editorconfig
.github/workflows/build.yml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/BinaryPathTest.kt

Add head request for gradle download (#165)

---

.mvn/wrapper/maven-wrapper.properties
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/DayMeter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/StatsInterceptor.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/BinaryResource.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/SortOrder.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/JvmImpl.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/OperatingSystem.kt
adoptopenjdk-api-v3-persistance/pom.xml
adoptopenjdk-api-v3-updater/pom.xml
pom.xml

Bring metrics upgrades to master

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/BinaryPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/InstallerPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/packages/PackageEndpointTest.kt

Add installer endpoint

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/BinaryFilter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt

add date filter to feature_releases path (#177)

---

.github/workflows/build.yml

This PR adds `--batch-mode` to maven commands to prevent it printing many thousands of lines of download statuses in build logs. It also:
* Bumps build jdk version to 11.0.7
* Uses multi-line blocks for readability of complex step scripts

Reduce noise in build logs, update build jdk to 11.0.7

---

CONTRIBUTING.md

A few details missing required to set-up
Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

Add setup details to documentation

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/DownloadStatsPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/MonthlyStatsPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/MonthlyDownloadDiff.kt
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/DownloadStatsInterface.kt

Issue: https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/129
- `jvm_impl` can now be used in `/tracking` to filter those results. Works with all of the other filters.
- `feature_version` can now be used with `source=dockerhub`
- Both of these do not include results from the official docker repository, which is detailed in the descriptions
- Grabs the last entry of each month and uses that as the "final total for that month"
- Monthly stat is calculated between the final totals of each month
- Returns data in the format:
```
{
"month": "2020-May",
"monthly": 100,
"total": 350
}
```
- Currently does this for the last 6 months (inc current month)
- Can manually set the `to` date for this. No `from` yet
- Will probably add a `months` filter, similar to how `days` works for `/tracking`
- …

New monthly endpoint and adding jvmImpl filter

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/Pagination.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ReleaseNamesPathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionPathTest.kt

The `page_size` query parameter was incorrectly handled in `AssetsResource` and capped to an undocumented limit of 20 items per page.
In `ReleaseListResource`, the `page_size` query parameter wasn't used at all, although documented in the API specification (via Swagger).
Fixes #184

Fix `page_size` parameter in AssetsResource and ReleaseListResource

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/platforms.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Architecture.kt

Closes: https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/224
Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

Add riscv architecture to api

---

adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt

When the tests are executed a number of attempts are made to initialise the
MongoClient before the Mongo instance has been initialised. By default, this
triggers a 30000ms timeout for each attempt.
The 'fallback' Mongo connection string is only used when the
Mongo user & password environment variables are not passed and therefore
only applies for local development/testing use-cases.
This change shortens the timeout to 100ms reducing overall test suite execution
time from ~40 mins to ~8 mins.
Fixes #238

Explicitly set serverSelectionTimeoutMS for 'fallback' Mongo connection string

---

adoptopenjdk-api-v3-persistance/pom.xml
adoptopenjdk-api-v3-persistance/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClient.kt
adoptopenjdk-api-v3-persistance/src/test/kotlin/net/adoptopenjdk/api/v3/dataSources/persitence/mongo/MongoClientTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/BaseTest.kt

This PR aims to clarify and simplify the login for the MongoClient connection string.
The changes are:
- Rename the `MONGO_DB` property set in `BaseTest` to `MONGODB_TEST_CONNECTION_STRING` 
- from the code this value is only used by tests so this name makes its intent clearer
- if in fact this is used for other purposes (e.g. production config) then we can revert this and document it
- Test the value of `MONGODB_TEST_CONNECTION_STRING` (previously `MONGO_DB`) first when initialising the MongoClient
- when non-null it overrides any previous values so it makes sense from a logic perspective to check this first
- Clearly log which connection string is being used when `MongoClient` is initialised
- this is useful for debugging purposes whereas previously a potentially misleading connection …

Refactor mongo client connection string

---

adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/AppInsightsInterceptor.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/V1Route.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
adoptopenjdk-api-v3-frontend/src/main/resources/ApplicationInsights.xml
adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
pom.xml

add application insights

---

adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathSortOrderTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Asset.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Installer.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Package.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/ReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamBinaryMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/upstream/UpstreamReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReleaseMapperTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposTest.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt

Identifies `.json` assets for an archive (.tar.gz, .zip) and exposes against the Package as a metadata_link.
Fixes #235 and #236

Expose metadata_link for binary assets

---

docs/adr/0002-branching-and-release-strategy.md

I've created this ADR following a conversation with @johnoliver. Hopefully it reflects what we discussed accurately but if not we can use this PR to evolve the decision to a state where ot can be accepted and applied to the project.
The decision goes some way to simplify how people contribute to the project however there remains the manual process of synchronising `master` and `production`/`release`. 
It would be nice not to require a separate branch to represent `production`.
We discussed a possible alternative that would be to hook into Git tags and GitHub releases, with a new production deployment being triggered by the release (i.e. tag) of the `master` branch. While it seems desirable, there's more complexity in there that I'm unable to explore as I don't fully understand the …

Branching & Release Strategy ADR

---

.s2i/bin/assemble
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequest.kt

Remove log left from build process

---

adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/SemverParser.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/TestSemverParser.kt

possible semver incompatibility fix

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/OpenApiDocs.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/VersionRangeFilter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VersionData.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/InvalidVersionSpecificationException.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/Restriction.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/VersionRange.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionRangeTest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHMetaData.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
pom.xml

This changes our filter ranges from accepting a semver into taking a java version, this change should be backwards compatible.
This involved bringing in the version range filter from maven and customising it for our versions.

Possible Solution to java patch version issue

---

.github/workflows/build.yml
FAQ.md
README.md
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/OpenApiDocs.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/VersionRangeFilter.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/PackageEndpoint.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceFeatureReleasePathTest.kt
adoptopenjdk-api-v3-models/pom.xml
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Binary.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VersionData.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/VersionParser.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/InvalidVersionSpecificationException.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/Restriction.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/parser/maven/VersionRange.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionRangeTest.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/models/GHMetaData.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptBinaryMapperTest.kt
pom.xml

Includes patch version parsing fix

Take staging changes live

---

CONTRIBUTING.md

Updates to the CONTRIBUTING.md guide based on [ADR2](https://github.com/AdoptOpenJDK/openjdk-api-v3/blob/master/docs/adr/0002-branching-and-release-strategy.md) and #284. 
Merging of this PR should be coordinated with the changes to the branches and OpenShift deployment strategy.

ADR2 Branching & release strategy contributing guide updates

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt

Add `info` logging when we have version and date parsing errors. This is likely just the client sending bad data, this logging will help confirm that either way.
See #342

Log version/date parsing errors

---

adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/models/Releases.kt
adoptopenjdk-api-v3-models/src/test/kotlin/net/adoptopenjdk/api/VersionParserTest.kt

Ignore internal PREs to fix openj9 nightly sort order

---

adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt

Usually generators like `openapi-generator` create unusable method names, so this PR overrides them by supplying usable names through `operationId` property of openapi specification

Add operationId to public endpoints

---

adoptopenjdk-api-v3-frontend/src/main/resources/JSON/variants.json
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/ApiDataStoreStub.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AvailableReleasesPathTest.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/ReleaseInfo.kt
adoptopenjdk-api-v3-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/Variant.kt
adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStoreImpl.kt
adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/ReleaseVersionResolver.kt
adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt

* Adds a new attribute (obsolete_releases) to /v3/info/available_releases that lists releases that have reached their end of life.
* Follow up to #314 which was a wontfix due to retiring of staging branch
Closes: #206 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

Obsolete Master

---

.github/workflows/build.yml
.github/workflows/publish.yml
adoptopenjdk-api-v3-frontend/pom.xml
adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt
adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/AssetsResourceVersionPathTest.kt
pom.xml

Creates an action that creates a `maven` branch in git, into this branch maven assets get checked in.
Publishing to git a temporary stopgap until we can publish to a real maven repo

Add action to publish maven assets

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/filters/VersionRangeFilter.kt
adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/VersionRangeFilterTest.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-models/src/test/kotlin/api/VersionParserTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-datasources-parent/adoptopenjdk-github-datasource/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/github/graphql/clients/GraphQLGitHubReleaseRequest.kt

Since pre-releases are less than full releases, `17.0.0-beta` is less than `17.0.0` this means that if asking for a filter of `16.0.0 < version < 17.0.0`, someone would expect this to return ONLY 16 versions, however since `17.0.0-beta < 17.0.0`, `17.0.0-beta` will be included. This although possibly technically correct is not what users would expect. As a solution strip out pre when performing a range match.

Fix version range filter unexpectedly including pre-release versions

---

.s2i/bin/assemble

Fix assembly moving to the wrong dir

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/SwaggerUiRoute.kt
adoptopenjdk-models-parent/adoptopenjdk-api-v3-adopt-specific-models/src/main/kotlin/net/adoptopenjdk/api/v3/models/VendorSchemaRef.kt

For some reason `/swagger-ui` is not redirecting to `/q/swagger-ui` explicitly add the redirect

Fix swagger redirect

---

adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/SwaggerUiRoute.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/StatsInterface.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterface.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptOpenJdk.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/stats/dockerstats/DockerStatsInterfaceAdoptium.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/DockerStatsInterfaceTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/StatsCalculatorTest.kt
adoptopenjdk-updater-parent/adoptopenjdk-mappers-parent/adopt-mappers/src/main/kotlin/net/adoptopenjdk/api/v3/mapping/adopt/AdoptReleaseMapper.kt

Backport adoptium fixes:
- Apply swagger routes.
- Fix dockerstats at adoptium

Bring in upstream changes
